### ISSUE TITLE
Some questions should have "I don't know/I never thought about it"

### ISSUE THREAD

**Issue by mvdoc** [psychoinformatics-de/dmc#15]
For example 'Open Hardware' or 'Open Software' questions.

**Comment by hanke** [comment]
I'd rather prefer that people don't have "dont want to think about it options". If they don't care than "Not at all is what they should click" IMHO.

**Comment by mvdoc** [comment]
Well, in my own case I never thought before about open hardware, as I never
had a reason to look into that. But of course this is something I would
definitely weigh important. What I'm saying is that the survey assumes that
who takes it already knows about this stuff.

**Comment by Alexqw** [comment]
@mvdoc The survey is just asking about this point in time. If you never considered it, then it obviously wasn't important to you.

However, the idea is that (hopefully soon) respondents will be able to update your response. So if your experience/opinions/stats change over time, you can update your survey with that info.

Perhaps the question needs to be adjusted. Some hardware is truly open source (Sun released designs of SPARC long ago), but mostly I was referring to drivers, and availabilty for other (open) tools to work with the hardware. Intel (open) vs Broadcom (shoot me now). MacBook Pro vs ThinkPad. Etc.

@hanke Thoughts?

**Comment by hanke** [comment]
I think it should stay as is for now. If it makes visitors think about novel aspects: even better. Re Matteo's concrete case: Initial response should be (IMHO) "not at all". The next update might be different, indeed.

"Don't know" would be equivalent to "not important" -- the argument in favor of don't know would be: I would have cared, if I would have thought about it. But that is not what we are interested in. We want to know what motivates people to make their decisions.

**Comment by mvdoc** [comment]
OK :)
