### ISSUE TITLE
there should be a progress indicator

### ISSUE THREAD

**Issue by yarikoptic** [psychoinformatics-de/dmc#17]
one way or another... otherwise people might give up one answer short of finishing it up

**Comment by hanke** [comment]
There is an inverse progress indicator: The shorter the scrollbar thingie the closer you are to the end ;-)

**Comment by yarikoptic** [comment]
On Mon, 19 Oct 2015, Michael Hanke wrote:
> There is an inverse progress indicator: The shorter the scrollbar thingie the
> closer you are to the end ;-)

ha ;) ... not anyhow helpful though

**Comment by Alexqw** [comment]
@yarikoptic I've been thinking about this, and have some ideas. My current favorite is to put a pie-chart at the bottom of the timeline, and it will be filled in as the form progresses.

**Comment by yarikoptic** [comment]
As to me anything would work, eg a phrase ("95% complete, keep on good work"). Having some encouraging phrases (e.g. "50% complete, the point of no return") might keep participants interested to see which one will be next

**Comment by aqw** [comment]
While It would be nice to have, the survey isn't very long, and I don't have a clear idea, visually, where/how this would work.

@yarikoptic @mih Closing. But if anyone strongly objects, feel free to re-open.
