### ISSUE TITLE
tar: Option --transform is not supported

### ISSUE THREAD

**Issue by maysam** [psychoinformatics-de/dmc#21]
running make I get to this error

tar --transform 's,[A-Za-Z0-9\.-]*,cherrypy,' -xvf cherrypy.tar.gz
tar: Option --transform is not supported

tar seems to behave differently on mac vs linux

**Comment by aqw** [comment]
Now using mod_wsgi rather than cherrypy (b947f476feb0670a183e69a1e228aeafe7f686a6), and thus no more tar. Closing.

---Alex
