### ISSUE TITLE
form should be able to initialize values given UUID variable

### ISSUE THREAD

**Issue by hanke** [psychoinformatics-de/dmc#5]

**Comment by Alexqw** [comment]
This is done, but not pushed. The current blocker is #11. It's easy-ish to load the values into the fields. But showing them intelligently, that's going to require taking another look at how inter-field-dependencies are declared.

---Alex

**Comment by Alexqw** [comment]
Done in  592f678 and  84301ed, but they're not shown yet, which is what #11 is about.
